name: CI

on:
  push:
    branches: [ backlog/gh-build-and-release-on-pr ]
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  build-connect-package-linux:
    name: Build Connect package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install Connect
        run: |
          python -VV
          pip install -e git+https://github.com/ftrackhq/ftrack-connect.git@2.1.1#egg=ftrack_connect
          pip list
      - name: Install Connect deps
        run: |
          echo "Source contents:"
          ls -la /home/runner/work/ftrack-connect-package/ftrack-connect-package/src/ftrack-connect/source
          echo "Source parent contents:"
          ls -la /home/runner/work/ftrack-connect-package/ftrack-connect-package/src/ftrack-connect/source/..
          pip install /home/runner/work/ftrack-connect-package/ftrack-connect-package/src/ftrack-connect/source/../requirements.txt
      - name: Install Connect package deps
        run: |
          pip install -r requirements.txt
          pip list
      - name: Build plugin
        run: |
          python setup.py build_exe
      - name: Compress plugin
        run: |
          cd dist
          tar -zcvf ftrack-connect-package-${{ github.ref }}.tar.gz exe.linux-x86_64-3.7 --transform 's/exe.linux-x86_64-3.7/ftrack-connect-package/'
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Please check PR for details.
          draft: false
          prerelease: true
      - uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "build/*.tar.gz"
          release_id: ${{ steps.create_release.outputs.id }}
          overwrite: true
          verbose: true