name: CI

on:
  push:
    branches: [ backlog/gh-build-and-release-on-pr ]
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  build-connect-package:
    name: Build Connect package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - with:
          python-version: '3.7'
      - name: Install Connect
        run: |
          python -VV
          pip install -e git://github.com/ftrackhq/ftrack-connect.git@2.1.1
          pip list