name: CI

on:
  push:
    branches: [ backlog/gh-build-and-release-on-pr ]
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  build-connect-package-linux:
    name: Build Connect package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install deps
        run: |
          python -VV
          pip install -r requirements.txt
          pip list
      - name: Install Connect
        run: |
          pip install -e git+https://github.com/ftrackhq/ftrack-connect.git@2.1.1#egg=ftrack_connect
          pip list
      - name: Build plugin
        run: |
          python setup.py build_exe